version: '4'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - '.:/var/www/html'

  db:
      image: mysql:5.6
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: web_db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
      volumes:
        - db-data:/var/lib/mysql

  volumes:
    db-data: