version: '4'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80

  web_db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: web_DB
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306
