version: '4'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    volumes:
      - '.:/var/www/html'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: web_DB
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 33063:3306
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql

volumes:
  db-data:
